env:
  browser: true
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  no-param-reassign: 0
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  import/extensions:
    - error
    - ignorePackages
    - js: always
